# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - checkout: self
    clean: true

  - script: |
      set -e
      sudo apt-get update
      sudo apt install zlib1g-dev libz-dev libdbus-1-dev libpcre3-dev cmake
      git clone https://$(user):$(password)@github.com/easybyte-software/konga.git
      wget https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.4.2.tar.gz
    displayName: 'Download dependencies'

  - script: |
      tar -zxvf mpdecimal-2.4.2.tar.gz
      cd mpdecimal-2.4.2
      ./configure
      CFLAGS=-fPIC make -j2
      sudo make install
      cd ..
    displayName: 'Installing mpdecimal'
  
  - script: |
      cd konga
      mkdir -p out
      cd out
      cmake .. -DOPT_USE_CPP11=1 -DOPT_NO_SSL=1 -DOPT_KONGALIB_WHEEL=1
      make
      sudo make install
      cd ../..
    displayName: 'Installing ebpr and konga_client'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  
  - script: |
      python -m pip install -U pip
      pip install -U setuptools wheel
      python setup.py bdist_wheel
    displayName: 'Building wheel'
  
  - task: CopyFiles@2
    inputs:
      contents: dist/*.whl
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Linux wheels'

- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - checkout: self
    clean: true

  - script: |
      set -e
      brew install zlib pcre
      git clone https://$(user):$(password)@github.com/easybyte-software/konga.git
      wget https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.4.2.tar.gz
    displayName: 'Download dependencies'

  - script: |
      tar -zxvf mpdecimal-2.4.2.tar.gz
      cd mpdecimal-2.4.2
      ./configure
      CFLAGS=-fPIC make -j2
      sudo make install
      cd ..
    displayName: 'Installing mpdecimal'
  
  - script: |
      cd konga
      mkdir -p out
      cd out
      cmake .. -DOPT_USE_CPP11=1 -DOPT_NO_SSL=1 -DOPT_KONGALIB_WHEEL=1
      make
      sudo make install
      cd ../..
    displayName: 'Installing ebpr and konga_client'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      export MACOSX_DEPLOYMENT_TARGET="10.8"
      python -m pip install -U pip
      pip install -U setuptools wheel
      python setup.py bdist_wheel
    displayName: 'Building wheel'
  
  - task: CopyFiles@2
    inputs:
      contents: dist/*.whl
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'macOS wheels'
