steps:

- script: |
    call "$(vcvarsall)" $(python.architecture)
    set KONGASDK=$(Build.SourcesDirectory)\third_party
    python setup.py bdist_wheel -d wheelhouse
  displayName: 'Build wheel (Windows)'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- script: |
    export MACOSX_DEPLOYMENT_TARGET="10.10"
    export KONGASDK=$BUILD_SOURCESDIRECTORY/third_party
    python -m pip wheel -vvv . -w wheelhouse/
  displayName: 'Build wheel (macOS)'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

- script: |
    ls -lh wheelhouse
    mkdir -p dist
    cp wheelhouse/kongalib* dist/.
  displayName: 'Show wheelhouse'

- script: |
    python -m pip download colorama -d wheelhouse
    python -m pip install kongalib --no-index -f wheelhouse
  displayName: 'Install wheel'

- script: |
    python -m pip install delocate
    /Library/Frameworks/Python.framework/Versions/$(python.version)/bin/delocate-wheel dist/kongalib*.whl
  displayName: 'Delocate wheels'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin')) 
