steps:

- task: TwineAuthenticate@0
  inputs:
    artifactFeeds: easybyte-software
    externalFeeds: pypi

- ${{ if eq(parameters.publish_param, true) }}:
  - script: |
      twine upload -r pypi --config-file $(PYPIRC_PATH) dist/*
    displayName: 'Upload wheels to PyPI'
    condition: succeeded()

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: '$(Agent.OS)_$(Agent.JobName)_$(python.architecture)'
    targetPath: 'dist'
