steps:

- task: TwineAuthenticate@0
  inputs:
    artifactFeeds: easybyte-software
    externalFeeds: pypi

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: '$(Agent.OS)_$(Agent.JobName)_$(python.architecture)'
    targetPath: 'dist'
