steps:

- script: |
    call "$(vcvarsall)" $(python.architecture)
    if "$(python.version)"=="2.7" (
      set MSSdk=1
      set DISTUTILS_USE_SDK=1
      copy /Y $(Build.SourcesDirectory)\kongautil.py $(Build.SourcesDirectory)\doc\_static
      copy /Y $(Build.SourcesDirectory)\kongaui.py $(Build.SourcesDirectory)\doc\_static
    )
    set KONGASDK=$(Build.SourcesDirectory)\third_party
    python -m pip wheel . -w wheelhouse/
  displayName: 'Build wheel (Windows)'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- script: |
    python -m pip wheel . -w wheelhouse/
  displayName: 'Build wheel (macOS)'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

- script: |
    ls -lh wheelhouse
    mkdir -p dist
    cp wheelhouse/kongalib* dist/.
  displayName: 'Show wheelhouse'

- script: |
    python -m pip install kongalib --no-index -f wheelhouse
  displayName: 'Install wheel'

- script: |
    python -m pip install delocate
    /Library/Frameworks/Python.framework/Versions/$(python.version)/bin/delocate-wheel dist/kongalib*.whl
  displayName: 'Delocate wheels'
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin')) 
