steps:

- script: |
    if [ "$(verbose)" != "true" ]; then docker run --rm -v `pwd`:/io -e "VERBOSE=0" -e "KONGALIB_ROOT=/io" $(image) /io/.azure-pipelines/build-wheels.sh; fi
    if [ "$(verbose)" == "true" ]; then docker run --rm -v `pwd`:/io -e "VERBOSE=1" -e "KONGALIB_ROOT=/io" $(image) /io/.azure-pipelines/build-wheels.sh; fi
  displayName: Build wheels

- script: |
    ls -lh wheelhouse/
    mkdir -p dist
    cp wheelhouse/kongalib*manylinux*.whl dist/.
  displayName: Show and copy wheels

- script: |
    python -m pip install --upgrade pip
    python -m pip install twine
  displayName: 'Install twine'
