trigger:
- master

parameters:
- name: publish_param
  displayName: Publish wheels by uploading to PyPI
  type: boolean
  default: false
- name: sdk_version_param
  displayName: Version of the Konga SDK to be used
  type: string
  # this should be changed back to "current" after 2.0.0 release
  default: stable/2.0.0-beta

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'

- job: macos
  pool: {vmImage: 'macOS-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        python3 -m pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - bash: |
        curl https://public.easybyte.it/downloads/${{ parameters.sdk_version_param }}/sdk?os=mac -o KongaSDK.dmg
        7z e -aoa KongaSDK.dmg && sudo installer -pkg KongaSDK.pkg -target /
      displayName: Install Konga SDK
    - bash: |
        ls -l /usr/local/lib
        ls -l /usr/local/include
      displayName: Show /usr/local
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: wheelhouse

- job: windows
  pool: {vmImage: 'windows-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - powershell: |
        Invoke-WebRequest https://public.easybyte.it/downloads/${{ parameters.sdk_version_param }}/sdk?os=win -OutFile $(System.DefaultWorkingDirectory)\KongaSDK.exe
        Start-Process $(System.DefaultWorkingDirectory)\KongaSDK.exe -ArgumentList "/quiet" -Wait
      displayName: Install Konga SDK
    - powershell: |
        dir env:
      displayName: Show env
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'