trigger:
- master

parameters:
- name: publish_param
  displayName: Publish wheels by uploading to PyPI
  type: boolean
  default: false
- name: sdk_version_param
  displayName: Version of the Konga SDK to be used
  type: string
  # this should be changed back to "current" after 2.0.0 release
  default: stable/2.0.0-beta
- name: platform_param
  displayName: Platform filter [windows|darwin|linux|*]
  type: string
  default: *

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'
  condition: or(eq('${{ parameters.publish_param }}', 'linux'), eq('${{ parameters.publish_param }}', '*'))

- job: macos
  pool: {vmImage: 'macOS-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        python3 -m pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - bash: |
        curl https://public.easybyte.it/downloads/${{ parameters.sdk_version_param }}/sdk?os=mac -o KongaSDK.dmg
        7z e -aoa KongaSDK.dmg && sudo installer -pkg KongaSDK.pkg -target /
      displayName: Install Konga SDK
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: wheelhouse
  condition: or(eq('${{ parameters.publish_param }}', 'darwin'), eq('${{ parameters.publish_param }}', '*'))

- job: windows
  pool: {vmImage: 'windows-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - powershell: |
        Invoke-WebRequest https://public.easybyte.it/downloads/${{ parameters.sdk_version_param }}/sdk?os=win -OutFile $(System.DefaultWorkingDirectory)\KongaSDK.exe
        Start-Process $(System.DefaultWorkingDirectory)\KongaSDK.exe -ArgumentList "/install /quiet" -Wait
      displayName: Install Konga SDK
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
      env:
        KONGASDK: 'C:\Program Files\EasyByte\Konga SDK'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'
  condition: or(eq('${{ parameters.publish_param }}', 'windows'), eq('${{ parameters.publish_param }}', '*'))
