trigger:
- master

parameters:
- name: publish_param
  displayName: Publish wheels by uploading to PyPI
  type: boolean
  default: false
- name: verbose_param
  displayName: Build C dependencies verbosely
  type: boolean
  default: false
- name: konga_branch_param
  displayName: Branch from which to fetch Konga sources
  type: string
  default: stable-1.8.2

variables:
  konga_branch: ${{ parameters.konga_branch_param }}
  verbose: ${{ parameters.verbose_param }}
  publish: ${{ parameters.publish_param }}

jobs:

- job: LinuxSDist
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    python.architecture: 'none'
  steps:
    - script: |
        python -m pip install setuptools
        python setup.py sdist
      displayName: Publish sdist
    - template: ./azure-publish-dist.yml

- job: ManyLinux
  strategy:
    matrix:
      64Bit:
        arch: x86_64
        plat: manylinux2010_x86_64
        image: quay.io/pypa/manylinux2010_x86_64
        python.architecture: x64
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ./azure-setup.yml
    - template: ./azure-manylinux-wheels.yml
    - template: ./azure-publish-dist.yml

- job: macOS
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - template: ./azure-setup.yml
    - template: ./azure-steps.yml
    - template: ./azure-publish-dist.yml

- job: Windows
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        python.architecture: 'x64'
        vcvarsall: 'C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat'
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      Python37:
        python.version: '3.7'
        python.architecture: 'x64'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      Python38:
        python.version: '3.8'
        python.architecture: 'x64'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      Python27_32:
        python.version: '2.7'
        python.architecture: 'x86'
        vcvarsall: 'C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat'
      Python36_32:
        python.version: '3.6'
        python.architecture: 'x86'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      Python37_32:
        python.version: '3.7'
        python.architecture: 'x86'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
      Python38_32:
        python.version: '3.8'
        python.architecture: 'x86'
        vcvarsall: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ./azure-setup.yml
    - template: ./azure-steps.yml
    - template: ./azure-publish-dist.yml
