trigger:
- master

parameters:
- name: publish_param
  displayName: Publish wheels by uploading to PyPI
  type: boolean
  default: false
- name: sdk_version_param
  displayName: Version of the Konga SDK to be used
  type: string
  default: latest

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        pip3 install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'

- job: macos
  pool: {vmImage: 'macOS-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python3 -m pip install --upgrade pip
        python3 -m pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - task: PythonScript@0
      inputs:
        scriptPath: '.azure-pipelines/install_konga_sdk.py'
        arguments: '${{ parameters.sdk_version_param }} mac'
      displayName: Install Konga SDK
    - bash: |
        ls -l /usr/local/lib
        ls -l /usr/local/include
      displayName: Show /usr/local
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: wheelhouse

- job: windows
  pool: {vmImage: 'windows-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        set -o errexit
        python -m pip install --upgrade pip
        pip install requests cibuildwheel==2.12.3
      displayName: Prepare build environment
    - task: PythonScript@0
      inputs:
        scriptPath: '.azure-pipelines/install_konga_sdk.py'
        arguments: '${{ parameters.sdk_version_param }} win'
      displayName: Install Konga SDK
    - bash: cibuildwheel --output-dir wheelhouse .
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'wheelhouse'