steps:

- script: |
    docker run --rm -v `pwd`:/io $(image) /io/azure-pipelines/build-wheels.sh
  displayName: Build wheels

- script: |
    ls -lh wheelhouse/
    mkdir -p dist
    cp wheelhouse/kongalib*manylinux*.whl dist/.
  displayName: Show and copy wheels
